use_frameworks!

platform :ios, '10.0'

target 'HCPlayerFramework_Example' do
  pod 'HCPlayerFramework', :path => '../'

  target 'HCPlayerFramework_Tests' do
    inherit! :search_paths

    
  end
end
